# Info about you
name: TinyFish
position: Firmware Engineer
email: nepood@gmail.com
#company_name: Focaltech System Technology CO.,Ltd
#company_url: https://www.yourcompany.com
place_name: Shenzhen, Guangdong, China

# Blog info
title: TinyFish's Blog
description: This is my private blog system
url: https://huhumt.github.io
main_github_io: true
long_description: >-
    Hi! This is my own blog system to record my daily life.

# Social links
github_url: https://github.com/huhumt
#linkedin_url: http://www.linkedin.com/in/your-name
social:
  links:
    - https://github.com/huhumt

# Images + files
logo: assets/img/headshot.jpg
#cv_url: assets/files/cv.pdf
#resume_url: assets/files/resume.pdf

# Blog settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
highlighter: rouge
color_mode: light #auto  # auto, light, or dark
comments: false
disqus_shortname: none
syntax_highlight_stylesheet: syntax_highlight.css

# Colors - light mode
colors:
  text: 282828
  tag: dbefdc
  tag_hover: 93cf95
  header_background: d8e0f2 #2b422b
  header_text: dbefdc
  header_link_hover: 93cf95
  links: 459c48
  links_visited: 357a38

# Colors - dark mode
colors_dark:
  background: 333
  text: ccc
  tag: 2e6830
  tag_hover: 93cf95
  header_background: 232
  header_text: 93cf95
  header_link: 93cf95
  header_link_hover: 459c48
  links: 459c48
  links_visited: 357a38
